### ISSUE TITLE
Calling phone number from Twilio Client Android

### ISSUE THREAD

**Issue by yfsx** [twilio/twilio-client-quickstart-android#23]
Hi, thanks for creating this library and tutorial, it's really amazing!

Currently I began working on project which can be used to call people to their Twilio clientName  and phoneNumber. I have successfully implemented call to Twilio clientName, but somehow i can't make outgoing call to phone number. 

Is there any extra settings or any prerequisite that I didn't do before implementing call phone number by Twilio?

Thanks!

**Comment by tmconnors** [comment]
Hi @yfsx 

Did you created your own TwiML response or are using the [mobile-quickstart](https://github.com/twilio/mobile-quickstart)?

If you're using the mobile-quickstart, is the [CALLER_ID](https://github.com/twilio/mobile-quickstart/blob/master/server.py#L13) set with your Twilio number?

Have you linked Voice option for the Twilio number to the proper TwiML app or webhook in the account portal?

If you're still having issues shoot me your `APP_SID` - tconnors@twilio.com

**Comment by tmconnors** [comment]
The specific geo location was not enabled in their Account Portal.

**Comment by rakesh-ideal** [comment]
@tmconnors I also getting this issue, I set CALLER_ID and added TwiML app in the account portal,
But unable to make outgoing call to phone number ? 

I 'm not getting your point "The specific geo location was not enabled in their Account Portal."
Where i can check this in Account Portal ?

**Comment by yfsx** [comment]
hi @rakesh-ideal, earlier @tmconnors mention about country that available to use this feature.. You can check it on your dashboard, in your Account Portal go to Programmable Voice --> Settings --> Geo Permissions. You can ask for permission for using this service on your designated country..

cheers

**Comment by rakesh-ideal** [comment]
Thanks @yfsx Its working,
One more thing, now I can make call only for verified numbers,
How i can call to unverified numbers ?  
If not then can we verify a number problematically using Twilio Client ?

**Comment by yfsx** [comment]
i think after you enable that, you can make call to both verified and unverified number.. if anything goes wrong, you should ask @tmconnors directly or open new issue :)

**Comment by rakesh-ideal** [comment]
No, i cant make call to unverified number,
Is it required to verify numbers, when my account is in trial mode, after upgrade my account can i call to unverified numbers also ?
