### ISSUE TITLE
IllegalStateException: Unable to retrieve AudioTrack pointer for getPosition()

### ISSUE THREAD

**Issue by davidvoiq** [twilio/twilio-client-quickstart-android#30]
Hi Twilio team, we are facing this crash in our production app since the Twilio SDK was updated to 1.2.16 and still happening on Twilio SDK 1.2.17

```
com.twilio.client.quickstart E/AndroidRuntime: FATAL EXCEPTION: Thread-19094
                                                                              Process: com.twilio.client.quickstart, PID: 28434
                                                                              java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for getPosition()
                                                                                  at android.media.AudioTrack.native_get_position(Native Method)
                                                                                  at android.media.AudioTrack.getPlaybackHeadPosition(AudioTrack.java:654)
                                                                                  at com.twilio.client.impl.sound.SoundPoolPlayThread.run(SoundPoolPlayThread.java:126)
```
this only happens in devices running android 4.4, and happens as soon as we call `clientDevice.connect(...)`

attached is a [log in verbose mode](https://github.com/twilio/twilio-client-quickstart-android/files/420809/twilio_crash.txt) since we open the Twilio android quick start app and until it crashes (tapping in call button in the dialog which we input the number to call), please any help will be greatly appreciated because this is crashing our users when they try to start a call.

Thanks

**Comment by tmconnors** [comment]
Hi @davidvoiq, unfortunately I've been unsuccessful in reproducing the issue on a number of devices running 4.4.X. Is the crash occurring on all devices running 4.4 or a just subset? If that latter, a specific model would be helpful for debugging. Is this occurring in prod or dev? You can reach me directly at tconnors@twilio.com - would love to chat/help you.

**Comment by davidvoiq** [comment]
Hi @tmconnors and thanks for your help, this is happening to one of our main testers user, the model he is using to test the application is an LG G2 D803 running stock Android 4.4.4.
The crashes are happening in our dev and prod environments

**Comment by tmconnors** [comment]
@davidvoiq I tested on similar devices and was unable to reproduce the crash. I believe this is a specific device / os combo issue. I need to recreate the issue in order to properly diagnose. If you're willing I'd like to setup a session where I can remotely access the problematic device using [vysor](https://www.vysor.io/). Another option would be to mail us the device temporarily. Let me know if either of these options are acceptable - tconnors@twilio.com

**Comment by davidvoiq** [comment]
Hi @tmconnors as you suggested the crash has disappeared adding the  following lines to the creation of a Twilio device

```
private void createDevice(String capabilityToken) {
    try {
        if (clientDevice == null) {
            clientDevice = Twilio.createDevice(capabilityToken, this);
            // Add the following lines:
            clientDevice.setDisconnectSoundEnabled(false);
            clientDevice.setIncomingSoundEnabled(false);
            clientDevice.setOutgoingSoundEnabled(false);
....
```
The crash may be happening because of the **AudioTrack** is not configurated with a proper sound to be played in the Outgoing and Incoming and Disconnection events?

Maybe the Twilio SDK should be handling this error and if the **AudioTrack** has no file to be played not try to get his position and by so avoid those crashes?

**Comment by tmconnors** [comment]
@davidvoiq Some clarification. The file exists, however, the `LG G2 D803` cannot properly play the file. 

When using the Client library prior to 1.2.13, these sound files were included in the distribution `tar.bz2`. However, you had to manually import these **optional** sound files into your project. You mentioned you did not manually import any files other than the `twilio-client-android.jar`. This would explain why you never heard the notification sounds. No crash would occur on the `LG G2 D803` because it would not attempt to load/play a non existent file. I believe a crash would occur on this device if the sound files were imported into the project.

Starting in 1.2.14 the Client library is distributed as an `aar`. The sound files are automatically included with the package and available to your project. Now, unless the notification sounds are disabled the `LG G2 D803` will attempt to play them.

**Comment by davidvoiq** [comment]
Ok @tmconnors thanks for the clarification, as this issue is related to this specific device and we don't want to play a sound for the connection events, disabling the sounds is a good solution.

Thank you very much for your help. 👍

**Comment by grow2014** [comment]
Hello all.
I have the same issue. My log from Crashlytics:

_Fatal Exception: java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for getPosition()
       at android.media.AudioTrack.native_get_position(AudioTrack.java)
       at android.media.AudioTrack.getPlaybackHeadPosition(AudioTrack.java:1236)
       at com.twilio.client.impl.sound.SoundPoolPlayThread.run(SoundPoolPlayThread.java:126)_

Device: Samsung Galaxy S8 SM-G950U (Android 7.0)

Unfortunately, I do not have more information. There is the log only. What are you think about the crash?

**Comment by kbagchiGWC** [comment]
@grow2014 looking at the stack trace, I believe you are using our Video SDK. Can you create an issue under https://github.com/twilio/video-quickstart-android/issues. Please provide details, steps to reproduce and logs.

**Comment by kbagchiGWC** [comment]
@grow2014 - My bad, I misread the log and thought this was Video SDK related. Is this a device specific issue?

**Comment by grow2014** [comment]
@kbagchiGWC Hello **Kumkum**. I think no because it is the same issue like from @davidvoiq David.
But my customer has received the crash only once. 
I don't know him, so I have the log from Crashlytics only.

**Comment by kbagchiGWC** [comment]
@grow2014 We will try to reproduce the issue. In the meantime if you are able to reproduce or get additional information regarding steps to reproduce the issue, please let us know.

We strongly recommend you to move to using our next generation Voice SDK with better API and push notification support. You can find the details https://www.twilio.com/docs/api/voice-sdk/android.

**Comment by andrewgrow** [comment]
We have steps to reproduce the bug.

Library version `compile 'com.twilio:client-android:1.2.21'`

Devices with reproduce:
- Samsung Galaxy J7 (6.0.1)
- Samsung Galaxy Tab S2 (Android 7.0)
- Lenovo A7000 (Android 6)

Device that cannot reproduce:
- Google Pixel (Android 8.1.0)

1. Use android.hardware.Camera and play the snapsot sound for each action throught 
`new android.media.MediaActionSound().play(MediaActionSound.SHUTTER_CLICK);`
2. On the device we will take ~30-50 snapshots until the sound playing stop.
3. Attempt to call with Twillio

ActualResult: crash
```
FATAL EXCEPTION: Thread-3086
                                                                                Process: com.livegenic.selfservice_staging, PID: 6968
                                                                                java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for getPosition()
                                                                                    at android.media.AudioTrack.native_get_position(Native Method)
                                                                                    at android.media.AudioTrack.getPlaybackHeadPosition(AudioTrack.java:1092)
                                                                                    at com.twilio.client.impl.sound.SoundPoolPlayThread.run(SoundPoolPlayThread.java:126)
```

ExpectedResult: voice call

**Comment by kbagchiGWC** [comment]
@andrewgrow 


I was able to reproduce the exact problem you have described here by modifying the `ClientActivity` code. I updated the `connect(String contact, boolean isPhoneNumber)` to the following to play `MediaActionSound.SHUTTER_CLICK` sound 100 times in a loop:

```
/*
     * Create an outgoing connection
     */
    private void connect(String contact, boolean isPhoneNumber) {
        // Determine if you're calling another client or a phone number
        if (!isPhoneNumber) {
            contact = "client:" + contact.trim();
        }

        // play MediaActionSound.SHUTTER_CLICK
        MediaActionSound ms; 
        for (int i = 0; i < 100; i++) {
            ms = new android.media.MediaActionSound();
            ms.play(MediaActionSound.SHUTTER_CLICK);
        }

        Map<String, String> params = new HashMap<String, String>();
        params.put("To", contact);

        if (clientDevice != null) {
            // Create an outgoing connection
            activeConnection = clientDevice.connect(params, this);
            setCallUI();
        } else {
            Toast.makeText(ClientActivity.this, "No existing device", Toast.LENGTH_SHORT).show();
        }
    }
```

This code produced the crash below : 

```
02-26 00:33:13.161 26950-26950/com.twilio.client.quickstart E/AudioTrack: AudioFlinger could not create track, status: -12
02-26 00:33:13.178 26950-26950/com.twilio.client.quickstart E/SoundPool: Error creating AudioTrack
                                                                         
                                                                         --------- beginning of crash
02-26 00:33:13.179 26950-28657/com.twilio.client.quickstart E/AndroidRuntime: FATAL EXCEPTION: Thread-12
                                                                              Process: com.twilio.client.quickstart, PID: 26950
                                                                              java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for getPosition()
                                                                                  at android.media.AudioTrack.native_get_position(Native Method)
                                                                                  at android.media.AudioTrack.getPlaybackHeadPosition(AudioTrack.java:1236)
                                                                                  at com.twilio.client.impl.sound.SoundPoolPlayThread.run(SoundPoolPlayThread.java:126)
02-26 00:33:13.189 26950-26961/com.twilio.client.quickstart I/art: Background sticky concurrent mark sweep GC freed 16361(1331KB) AllocSpace objects, 0(0B) LOS objects, 29% free, 9MB/13MB, paused 16.637ms total 360.893ms
02-26 00:33:13.191 26950-26950/com.twilio.client.quickstart E/AudioTrack: AudioFlinger could not create track, status: -12
```

But the error did not happen if I reused the same instance of `MediaActionSound` to play `MediaActionSound.SHUTTER_CLICK`. In this case, `MediaActionSound` was initialized outside the for loop. So the code would look something like this : 

```
/*
     * Create an outgoing connection
     */
    private void connect(String contact, boolean isPhoneNumber) {
        // Determine if you're calling another client or a phone number
        if (!isPhoneNumber) {
            contact = "client:" + contact.trim();
        }
        // play MediaActionSound.SHUTTER_CLICK
        MediaActionSound ms = new android.media.MediaActionSound();
        for (int i = 0; i < 100; i++) {
            ms.play(MediaActionSound.SHUTTER_CLICK);
        }

        Map<String, String> params = new HashMap<String, String>();
        params.put("To", contact);

        if (clientDevice != null) {
            // Create an outgoing connection
            activeConnection = clientDevice.connect(params, this);
            setCallUI();
        } else {
            Toast.makeText(ClientActivity.this, "No existing device", Toast.LENGTH_SHORT).show();
        }
    }
```
Can you confirm if you are creating a new instance of `MediaActionSound` every time you need to play a sound or re-using the same instance?

Looking forward to hearing from you.

**Comment by andrewgrow** [comment]
@kbagchiGWC Hello! Thank you for your quick reaction! We may do Twillio better together ))

Yes, the crash is happen only if I create new instance of the MediaActionSound object every time I need to play a sound. 

I have changed my code to re-use instance of the MediaActionSound object and I do not have received the errors.

But I thought that my expirience will be useful for you. So I decided to write this.

**Comment by kbagchiGWC** [comment]
Thanks @andrewgrow. I am glad that your problem is resolved. 

Do consider moving to our next generation Voice SDK with better API and push notification support when possible. You can find the details [here](https://www.twilio.com/docs/api/voice-sdk/android). 

Let us know if we can help with anything.
