### ISSUE TITLE
Not able to connect to make VOIP calls

### ISSUE THREAD

**Issue by jadhavsuraj73** [twilio/twilio-client-quickstart-android#44]
I am using Twilio jar file SDK_VERSION = "1.2.13";
 Please find the details log attached in the file below.
[twilio-issue-log.txt](https://github.com/twilio/twilio-client-quickstart-android/files/973209/twilio-issue-log.txt)

**Comment by kbagchiGWC** [comment]
@jadhavsuraj73 I see the following transport error in the log, which indicates the application was not able to communicate with the Twilio Voice Service. Can you please check network availability and retry?

05-03 17:26:02.250 928-1004/<package-name> A/PJSIP: 17:26:02.250 tlsc0x90a5d814  TLS connect() error: Connection timed out [code=120110]
05-03 17:26:02.250 928-1004/<package-name> E/PJSIP: 17:26:02.250  tsx0x911d2064  Failed to send Request msg INVITE/cseq=18420 (tdta0x9d96b000)! err=120110 (Connection timed out)
05-03 17:26:02.250 928-1004/<package-name> D/PJSIP: 17:26:02.250  tsx0x911d2064  State changed from Calling to Terminated, event=TRANSPORT_ERROR

**Comment by kbagchiGWC** [comment]
@jadhavsuraj73 were you able to resolve the issue? Let me know if you need any debugging help.

**Comment by jadhavsuraj73** [comment]
@kbagchiGWC  Thanks a lot for your help and reply. I was able to connect from a different wifi network and mobile network. Looks like it was some firewall issue. Anyways, I really appreciate your help.
