### ISSUE TITLE
Unable to use setZOrderOnTop on VideoView

### ISSUE THREAD

**Issue by malcolmnguyen** [twilio/twilio-client-quickstart-android#50]
I'd like the one of the VideoViews to be on top of the UI window. In order to this we have to be able to `setZOrderOnTop`, however `VideoView.applyZOrder` uses the `setZOrderMediaOverlay` method which overrides `setZOrderOnTop`, this instead puts the surface below the window, but above other surface views. Im not sure when applyZOrder is being called but its overriding the desired effect im looking for.

[StackOverFlow](
https://stackoverflow.com/questions/5647824/android-multiple-surfaceviews/22746240#22746240)

**Comment by idelgado** [comment]
@malcolmnguyen please file this over at https://github.com/twilio/video-quickstart-android. This is the quickstart for Twilio Client, a VOIP calling SDK.
