### ISSUE TITLE
Problem with video call. supported formats could not be retrieved because an error occurred connecting to the camera service

### ISSUE THREAD

**Issue by viktord1985** [twilio/twilio-client-quickstart-android#51]
I have this error when I try to make video call with front camera: _Supported formats could not be retrieved because an error occurred connecting to the camera service. The crash is on second field_.
```
CameraCapturer cameraCapturer = new CameraCapturer(this, CameraCapturer.CameraSource.FRONT_CAMERA);
LocalVideoTrack localVideoTrack = LocalVideoTrack.create(this, true, cameraCapturer);
```
If I changing **FRONT_CAMERA** to **BACK_CAMERA** it works well. I have tested it on Nexus 5 and Galaxy s7 and it have the same crash.

**Comment by idelgado** [comment]
@viktord1985 please open this issue on https://github.com/twilio/video-quickstart-android
