### ISSUE TITLE
How to send the Caller's Name to the Callee with a CallInvite

### ISSUE THREAD

**Issue by BeanStalka** [twilio/twilio-client-quickstart-android#53]
If I have two twilio programmable voice  enabled tablets.  
Tablet A and Tablet B

Tablet A is Bob Smith's tablet

Tablet B is Jane Doe's tablet

When I initiate a call from Tablet A to Tablet B i need to be able to display who the call is from.

i.e. "Incoming call  from Bob Smith's Tablet"

So how do I pass the Caller's Name to the tablet being called so I can accomplish this.

P.S. - I know the device identifier is available on the CallInvite object, I need something more flexible.

Thanks in advance for your help,

Bean

**Comment by kbagchiGWC** [comment]
Hi @BeanStalka This is a Programmable Voice SDK question. Can you please move this ticket to https://github.com/twilio/voice-quickstart-android?
