### ISSUE TITLE
No implementation found for com.twilio.chat.Messages com.twilio.chat.Channel.getMessages

### ISSUE THREAD

**Issue by marcoRS** [twilio/twilio-client-quickstart-android#55]
```
implementation 'com.twilio:chat-android:0.12.2'
implementation 'com.twilio:accessmanager-android:0.1.0'
```

We are seeing the following error in our app:

```
Caused by java.lang.UnsatisfiedLinkError: 
No implementation found for com.twilio.chat.Messages com.twilio.chat.Channel.getMessages() (tried Java_com_twilio_chat_Channel_getMessages and Java_com_twilio_chat_Channel_getMessages__) at com.twilio.chat.Channel.getMessages(Channel.java)
```

This seems to be a native error but we are unsure on how to proceed to fix this.

**Comment by idelgado** [comment]
Please re-file this issue here: https://github.com/twilio/twilio-chat-demo-android. This quickstart is for a different SDK.

**Comment by kbagchiGWC** [comment]
Hi @marcoRS I  moved the issue under https://github.com/twilio/twilio-chat-demo-android. Here is the link https://github.com/twilio/twilio-chat-demo-android/issues/25.
