### ISSUE TITLE
Getting an error when attempting an outbound call from Android SDK 

### ISSUE THREAD

**Issue by BeanStalka** [twilio/twilio-client-quickstart-android#56]
I am getting a nasty error when I attempt to place a call from the most recent Android SDK.

Attached please find an abbreviated logcat

[TwilioError.txt](https://github.com/twilio/twilio-client-quickstart-android/files/1492336/TwilioError.txt)

**Comment by idelgado** [comment]
There are some cases where the OpenSLES Audio is not properly supported on emulators or devices. In this case as of beta24 we return an error. Previously this resulted in a crash. See https://www.twilio.com/docs/api/voice-sdk/android/changelog#200-beta24

**Comment by BeanStalka** [comment]
Do you have any suggestions on how to fix this?

A work around?

**Comment by idelgado** [comment]
Not at the moment. We are planning to move to a WebRTC based media stack in Q1 of 2018. This will provide substantially better audio capabilities including the ability to fallback to a non OpenSLES implementation.

What particular device or emulator do you see this on?

**Comment by idelgado** [comment]
We're you able to confirm that an error is returned using beta24?

**Comment by BeanStalka** [comment]
Yes, this error occurs with beta 24.

Trolling through the history is seem like this one comes and goes.  All the way back to beta 10 

https://github.com/twilio/voice-quickstart-android/issues/60
https://github.com/twilio/voice-quickstart-android/issues/61

Awaiting your advice for a work around.

Maybe there is a library that I can install as well to smooth over where ever this gap is?

Otherwise I will need to look into other software options. I just need Voip calls, and thats not that difficult.

**Comment by idelgado** [comment]
One point of clarification, are you getting a `AudioDeviceErrorException` from `onConnectFailure(...)` with beta24? Or are you still getting a native crash like what you posted above? On beta24 we don't expect to see the crash anymore, rather we will surface this error via `onConnectFailure(...)` with an `AudioDeviceErrorException`.

What device is this? If you are still seeing a crash on beta24 I'd like to try to reproduce locally.

**Comment by BeanStalka** [comment]
I am getting the crash in beta 24.  Looks like a regression issue.

**Comment by idelgado** [comment]
Is this specific to a device or an emulator? If it's an emulator I might be able to reproduce.

**Comment by BeanStalka** [comment]
I'm seeing this on my Samsung S2 Tablet (SM-T713)

What was the fix the last time you guys ran into this?

**Comment by BeanStalka** [comment]
Oh BTW it is not calling back into OnConnectionFailure.   Wanted to make that clear.  Just crashing

**Comment by idelgado** [comment]
You mentioned that this is a regression. Did this not crash in prior beta versions? Which beta version did this work on?

**Comment by BeanStalka** [comment]
I said this is a regession because you guys fixed it for the poor soul in issue #60:

_@aashu09 we have officially released the fix in beta14. We appreciate your feedback and effort for bringing this issue to our attention.Let me know if you have any questions._

This is an actual device, 

You cannot make a phone call with an emulator, you would need a mic.  Unless I missed some new tech, emulators don't have those. 

As I asked before what was the nature of the fix last time?  It could help me create a work around if I knew what broke the first time.

Be as specific as you can, I'm not going to hound you like the guy in #60.  I will just advise my team lead we need to look else ware for VOIP in our application.

Bean

**Comment by idelgado** [comment]
The crash log you provided looks entirely different than any of the logs posted in #60. While the function you are trying to perform is the same, placing an outgoing call, your stacktrace is entirely different.

In the log I see the Audio device failed to create an audio session and returned `SL_RESULT_CONTENT_UNSUPPORTED`. I don't have a fix to recommend for this now. We'll have to investigate further on our end.

```
11-21 16:57:06.322 I/libOpenSLES( 1844): Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x1 based on channel count of 1)
11-21 16:57:06.324 W/AudioTrack( 1844): AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 16000 Hz, output 48000 Hz
11-21 16:57:06.325 D/AudioTrack( 1844): Client defaulted notificationFrames to 460 for frameCount 1380
11-21 16:57:06.326 W/libOpenSLES( 1844): Conversion from OpenSL ES positional channel mask 0x4 to Android mask 0 loses channels
11-21 16:57:06.326 I/libOpenSLES( 1844): Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x10 based on channel count of 1)
11-21 16:57:06.328 E/AudioRecord( 1844): Could not get audio input for session 145, record source 7, sample rate 16000, format 0x1, channel mask 0x10, flags 0x1
11-21 16:57:06.328 E/libOpenSLES( 1844): android_audioRecorder_realize(0x82b2e200) error creating AudioRecord object; status -22
11-21 16:57:06.328 W/libOpenSLES( 1844): Leaving Object::Realize (SL_RESULT_CONTENT_UNSUPPORTED)
```

**Comment by idelgado** [comment]
Tracking this issue in the `voice-quickstart-android` repo
