### ISSUE TITLE
Facing dex error after adding Twilio dependency.

### ISSUE THREAD

**Issue by shahzad1** [twilio/twilio-client-quickstart-android#60]
I'm developing an Android app in which I wanna generate number programmatically for each user. I'm using below (Twilio) dependency in my project.
`compile group: 'com.twilio.sdk', name: 'twilio', version: '7.17.0'`
When I try to run the app, it gives me following error(See attached image). Any solution?
![dexerror](https://user-images.githubusercontent.com/10573828/36344544-1bf0a79c-143e-11e8-9ce4-9743849deb9e.JPG)

**Comment by idelgado** [comment]
The Java helper library you are trying to use is not compatible with Android. This library is intended to be used as part of a server component. You should use your own webservice that uses this library to generate the number.

**Comment by shahzad1** [comment]
Can you refer me complete code for generating number programmatically?

**Comment by idelgado** [comment]
This is an article that provides information and links to the REST API on purchasing phone numbers: https://support.twilio.com/hc/en-us/articles/223182728-Using-the-API-to-search-for-and-buy-Twilio-phone-numbers

**Comment by idelgado** [comment]
If you have more specific questions you can request support https://support.twilio.com/hc/en-us/requests/new and someone will provide you with more detailed information based on your use case.

**Comment by shahzad1** [comment]
I wanna know one more thing, If a user purchase Twilio number from my app, will he be able to recieve call and message on that (purchased) number?
