### ISSUE TITLE
Twilio number

### ISSUE THREAD

**Issue by shahzad1** [twilio/twilio-client-quickstart-android#61]
If a user purchase Twilio number from my app, will he be able to recieve call and message on that (purchased) number?

**Comment by shahzad1** [comment]
Still waiting for any response

**Comment by kbagchiGWC** [comment]
@shahzad1 This is not the right repository for Twilio Phone Number related questions. As @idelgado mentioned in https://github.com/twilio/twilio-client-quickstart-android/issues/60, please open a support ticket using this link https://support.twilio.com/hc/en-us/requests/new and someone will provide you with specific details.
