### ISSUE TITLE
I get connection failure in the Call.Listener

### ISSUE THREAD

**Issue by uriel-frankel** [twilio/twilio-client-quickstart-android#62]
In the Call.Listener I get onConnectFailure with this:

`03-15 18:32:25.559 12016-12016/com.houzz.app D/CallManager: onConnectFailure() called with: call = [com.twilio.voice.Call@bf8294], e = [com.twilio.voice.CallException: Connection error]
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err: com.twilio.voice.CallException: Connection error
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err:     at com.twilio.voice.CallControlManager.onCallState(CallControlManager.java:195)
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err:     at com.twilio.voice.impl.useragent.Call.makeCall(Native Method)
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err:     at com.twilio.voice.impl.useragent.Call.<init>(Call.java:29)
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err:     at com.twilio.voice.CallCommand.makeCall(CallCommand.java:62)
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err:     at com.twilio.voice.CallCommand.startCall(CallCommand.java:27)
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err:     at com.twilio.voice.BridgeCallCommand.run(BridgeCallCommand.java:17)
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err:     at android.os.Looper.loop(Looper.java:154)
03-15 18:32:25.560 12016-12016/com.houzz.app W/System.err:     at com.twilio.voice.CallCommandHandlerImpl.run(CallCommandHandlerImpl.java:59)`

This is only on one device.

**Comment by kbagchiGWC** [comment]
@uriel-frankel I believe you are using [Android Voice SDK](https://www.twilio.com/docs/api/voice-sdk). Can you please open the issue in https://github.com/twilio/voice-quickstart-android? Please provide details of the SDK version, reproducibility of failed scenario.
